//! 스토리 핵심 스포일러(메일 본문, 정체불명 개체 이름 placeholder)만 따로 모아둔
//! 파일 — `strings.rs`의 나머지 UI 문구(버튼/라벨 등)는 그냥 평문이어도 상관없지만,
//! 여기 있는 상수들은 실행 파일에 평문으로 남아있으면 `strings.exe` 한 번만 돌려도
//! ARG 정답/떡밥이 그대로 새어나간다. 나중에 안티 리버싱(문자열 암호화) 작업을 붙일
//! 때 이 파일 하나만 손대면 되도록 의도적으로 분리해뒀다.

use crate::strings::S;

// foundation.rs::FileSystem::new() 의 Photos 앱 이름이자, mail.rs 메일 본문에서도
// 같은 개체를 가리키는 데 쓰인다 — 두 곳이 반드시 같은 문자열이어야 하므로 상수로
// 공유한다.
pub const PHOTOS_APP_NAME: &str = "ЫЩЁЪЭ";

// 아직 별도 기능은 없고 메일 본문에서만 언급되는, 나중을 위한 떡밥용 개체 이름.
pub const UNNAMED_ENTITY: &str = "ЖЦЧШЮЯФ";

pub const PALACE_MAIL_SUBJECT: S = S {
    en: "PALACE OS Re-investigation Task Assignment",
    ko: "PALACE OS 재연구 업무 배정 안내",
    ja: "PALACE OS再調査業務の割り当てについて",
};

pub const PALACE_MAIL_BODY: S = S {
    en: "Welcome to the company, new researcher.\n\
         You have been assigned the re-investigation task for anomalous entity PALACE OS.\n\
         \n\
         PALACE OS has been generating image and video material over an extended period, and \
         previous research found no phenomena that caused direct harm to researchers, so its \
         safety class was maintained.\n\
         \n\
         However, cases have recently been confirmed where real-world phenomena match some of \
         the images generated by PALACE OS, and its danger class is currently under \
         reassessment.\n\
         \n\
         No record has been found of this entity inflicting physical injury on researchers, so \
         it has been determined that the re-investigation task for PALACE OS can be carried out \
         by a new researcher.\n\
         \n\
         Please carry out the following task during your working hours.\n\
         \n\
         Image Review\n\
         \n\
         Check the images generated in ЫЩЁЪЭ.\n\
         \n\
         If any of the following phenomena are present, send the image to us by mail.\n\
         \n\
         - Severe glitches\n\
         - Image corruption or cracking\n\
         - Unreasonable figures or shapes\n\
         - Unrealistic phenomena\n\
         \n\
         Please remember the following.\n\
         \n\
         - When sending mail to us, please close ЫЩЁЪЭ first.\n\
         - Do not install any program other than ours.\n\
         - Do not send ЫЩЁЪЭ to ЖЦЧШЮЯФ.\n\
         \n\
         We are not responsible for any harm resulting from your actions.\n\
         We wish all researchers a safe research experience.",
    ko: "자사에 입사하게 된 신입 연구원님을 환영합니다.\n\
         귀하에게 이상개체 PALACE OS의 재연구 업무가 배정되었습니다.\n\
         \n\
         PALACE OS는 장기간 이미지 및 영상 자료를 생성해 왔으며 기존 연구에서는 연구원에게 \
         직접적인 위해를 가하는 현상이 발견되지 않아 안전등급을 유지하고 있었습니다.\n\
         \n\
         그러나 최근 PALACE OS가 생성한 일부 이미지와 일치하는 현상이 확인되어 현재 \
         위험등급의 재심사가 진행되고 있습니다.\n\
         \n\
         해당 개체는 연구원에게 물리적인 상해를 입힌 기록이 확인되지 않았기에 PALACE OS의 \
         재연구 업무는 신입 연구원이 수행 가능하다고 판단되었습니다.\n\
         \n\
         귀하는 업무 시간 동안 다음 작업을 수행해 주십시오.\n\
         \n\
         이미지 검수\n\
         \n\
         ЫЩЁЪЭ에 생성된 이미지를 확인하십시오.\n\
         \n\
         다음 현상이 포함된다면 자사의 메일로 이미지를 보내십시오.\n\
         \n\
         - 심각한 글리치\n\
         - 이미지의 손상 또는 크랙\n\
         - 비상식적인 형체\n\
         - 비현실적인 현상\n\
         \n\
         반드시 기억하십시오.\n\
         \n\
         - 자사에 메일을 보낼 때는 ЫЩЁЪЭ를 닫고 보내십시오.\n\
         - 자사의 프로그램 외의 프로그램을 설치하지 마십시오.\n\
         - ЖЦЧШЮЯФ에 ЫЩЁЪЭ을 보내지 마십시오.\n\
         \n\
         귀하의 행동으로 인한 피해는 자사가 책임지지 않습니다.\n\
         자사는 모든 연구원들의 안전한 연구 활동을 기원합니다.",
    ja: "入社された新人研究員の皆様を歓迎いたします。\n\
         貴殿に異常個体PALACE OSの再調査業務が割り当てられました。\n\
         \n\
         PALACE OSは長期間にわたり画像および映像資料を生成してきましたが、これまでの \
         研究では研究者に直接的な危害を加える現象は確認されておらず、安全等級を \
         維持しておりました。\n\
         \n\
         しかし最近、PALACE OSが生成した一部の画像と一致する現象が確認され、現在危険等級の \
         再審査が進められています。\n\
         \n\
         当該個体が研究者に物理的な傷害を負わせた記録は確認されていないため、PALACE OSの \
         再調査業務は新人研究員でも遂行可能と判断されました。\n\
         \n\
         貴殿は勤務時間中、次の作業を行ってください。\n\
         \n\
         画像検収\n\
         \n\
         ЫЩЁЪЭで生成された画像を確認してください。\n\
         \n\
         次の現象が含まれている場合は、弊社のメールに画像を送ってください。\n\
         \n\
         - 深刻なグリッチ\n\
         - 画像の損傷またはクラック\n\
         - 非常識な形体\n\
         - 非現実的な現象\n\
         \n\
         必ず覚えておいてください。\n\
         \n\
         - 弊社にメールを送る際は、ЫЩЁЪЭを閉じてから送ってください。\n\
         - 弊社のプログラム以外のプログラムはインストールしないでください。\n\
         - ЖЦЧШЮЯФにЫЩЁЪЭを送らないでください。\n\
         \n\
         貴殿の行動による被害について、弊社は責任を負いません。\n\
         弊社はすべての研究員の安全な研究活動を祈念いたします。",
};
